### ISSUE TITLE
libsharp_jll recipe CFLAGS

### ISSUE THREAD

**Issue by xzackli** [ziotom78/Libsharp.jl#2]
Hey @ziotom78, I'm unfamiliar with BinaryBuilder, but it seems like the [recipe](https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/libsharp2/build_tarballs.jl) on Yggdrasil does not include some important CFLAGS for performance. The GitLab [COMPILE](https://gitlab.mpcdf.mpg.de/mtr/libsharp/-/blob/master/COMPILE) file recommends always using fast-math, and it seems like one should specify the non-portable binary for SIMD instructions, i.e.

```
CFLAGS="-DMULTIARCH -std=c99 -O3 -ffast-math"
```

**Comment by ziotom78** [comment]
Mmm… I'm not sure about the importance of all these flags:

- `-DMULTIARCH` is incompatible with `-march=WHATEVER`  (see Libsharp's [`COMPILE`](https://gitlab.mpcdf.mpg.de/mtr/libsharp/-/blob/master/COMPILE) file), which is used internally by BinaryBuilder to enable cross-compilation;

- `-std=c99` does not seem to affect the compilation of the code (which always happens using GCC 4.8.5);

- `-ffast-math` is [disabled](https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/610) by BinaryBuilder.jl because it makes dynamic libraries problematic to be used within Julia;

- `-O3` can be added.

I wonder if it's worth to add the `-O3` flag alone to the recipe; in other C++ libraries I developed, the difference in performance between using `-O2` and `-O3` has always been quite tiny. (It might be significant for libsharp2, however.)

@mreineck, I would like to have your take on this. What do you think?

**Comment by mreineck** [comment]
If this is a wrapper around the `libsharp` package from Github, then `MULTIARCH` will not do anything. `MULTIARCH` is a feature of the new libsharp version(s) hosted at https://gitlab.mpcdf.mpg.de/mtr/libsharp, which has an incompatible interface to the Github one.

I agree that `-std=c99` is no longer necessary for any recent compiler any more.

I don't really understand how `-ffast-math` can cause linker problems, but a quick search indicates that this can indeed have unwanted consequences when used for linking. `libsharp` relies on `-ffast-math` for performance, since without this flag the compiler is not allowed to generate fused multiply-and-add instructions, which can make a big difference.
If you compile `libsharp` with `-ffast-math` but don't use this flag when linking the full application, I think you should be OK...

`-O3` is helpful on some gcc versions because it enables more aggressive loop unrolling and inlining, which can help `libsharp` quite a bit.

**Comment by mreineck** [comment]
OK, I see now (sorry, too late) from the recipe that the `libsharp` in question comes from MPCDF. So `-DMULTIARCH` should definitely be effective.

I'm not too familiar with this approach of building ... is this meant to build a single binary package, which is then downloaded by many people on different (x86) hardware? Or is it meant to be compiled on every target machine?
In the first case, you should use `-DMULTIARCH` so that everyone gets the best possible performance, in the second case you can remove `-DMULTIARCH` and just use `-march=native` instead.

**Comment by ziotom78** [comment]
Hi @mreineck, thank you for chiming in. The `-DMULTIARCH` flag unfortunately produces the following errors:

```
[13:17:04] libsharp2/sharp_core.c: In function ‘have_avx512f’:
[13:17:04] libsharp2/sharp_core.c:73:1: error: Parameter to builtin not valid: avx512f
[13:17:04]  DECL(avx512f)
[13:17:04]  ^
[13:17:04] libsharp2/sharp_core.c: In function ‘have_fma4’:
[13:17:04] libsharp2/sharp_core.c:75:1: error: Parameter to builtin not valid: fma4
[13:17:04]  DECL(fma4)
[13:17:04]  ^
[13:17:04] libsharp2/sharp_core.c: In function ‘have_fma’:
[13:17:04] libsharp2/sharp_core.c:76:1: error: Parameter to builtin not valid: fma
[13:17:04]  DECL(fma)
[13:17:04]  ^
[13:17:04] make: *** [Makefile:868: libsharp2/sharp_core.lo] Error 1
[13:17:04]  ---> make
[13:17:04] Previous command exited with 2
[13:17:04] Child Process exited, exit code 2
```

> I'm not too familiar with this approach of building ... is this meant to build a single binary package, which is then downloaded by many people on different (x86) hardware? Or is it meant to be compiled on every target machine?

The target machine does not compile stuff, it is pre-compiled on a Travis machine (I believe) using a cross-compiler that targets different architectures and OS; you can see the list of artifacts produced for libsharp here: https://github.com/JuliaBinaryWrappers/libsharp2_jll.jl/releases

**Comment by mreineck** [comment]
On which platform does this happen? I could imagine that MULTIARCH may only be specified if you are compiling for an x86_64 target. I must admit that I never tried compiling for non-x86 hardware before, but I'm pretty sure that in such a situation you have to drop MULTIARCH.

**Comment by xzackli** [comment]
Regarding `-ffast-math`, could we replace it with the set of flags that it is a [shortcut](https://gcc.gnu.org/wiki/FloatingPointMath) for, which allows the floating point transformations?

My understanding is that linking with `-ffast-math` causes problems solely due to compilers like GCC also setting the FTZ and DAZ hardware bits when using the flag. These ensure there are no subnormals in hardware floating point calculations, but they do it globally (see https://github.com/JuliaCI/BaseBenchmarks.jl/issues/253, maybe @giordano knows of other issues?). 

I think there is a straightforward fix here: we enable every optimization within `-ffast-math` except for the subnormal treatment, and if subnormals are slowing us down in benchmarking, we can call the [wrapper within Julia](https://docs.julialang.org/en/v1/base/numbers/#Base.Rounding.set_zero_subnormals) for setting those, perhaps exposing a toggle in the Julia Libsharp wrapper which would enable it during SHT calls.

**Comment by mreineck** [comment]
> Regarding -ffast-math, could we replace it with the set of flags that it is a shortcut for, which allows the floating point transformations?

That should work fine.

**Comment by giordano** [comment]
`-ffast-math` is great to get wrong results faster and mess up with the global state and produce hard-to-track bugs in completely unrelated code

**Comment by mreineck** [comment]
As I'm mentioning in the COMPILE file, I'm not encouraging anyone to compile anything except the `libsharp` sources with this flag, and there is also no need to use it during linking. However I know from experiments over many years that it gives a big speedup for `libsharp` and that the results are not negatively affected by it.

I'll be more than happy to get rid of it, of course. But that will have to wait until `gcc` and other compilers reliably implement `#pragma STDC FP_CONTRACT`.

**Comment by mreineck** [comment]
I just did some measurements on my laptop. At least with this hardware, you can get almost the same performance if you replace `-ffast-math` by `-ffp-contract=fast`. So if you want to play it safe, that should be the way to go ... as far as I know, this flag has no link-time impact.

(In principle it's not even necessary to do this, since `gcc` usually has `-ffp-contract=fast` switched on. But if you (like me) use `-std=c99` to make sure the code is standard-conforming, the compiler disables floating-point contraction.

**Comment by giordano** [comment]
No one question the speed-up, but the problem with `-ffast-math` is especially that GCC changes the global CPU setting about flushing subnormals to zero _at loading time_, as shown in [the issue](https://github.com/JuliaCI/BaseBenchmarks.jl/issues/253) mentioned above.  You don't even need to call any function of the library, just open it.  Being a global option, this affects any program running on that CPU, not just the single library that was compiled with that option.

[This tweet](https://twitter.com/vchuravy/status/1216788090079076354) points you to the place in GCC code where this happens.

**Comment by mreineck** [comment]
I think we can agree that using `-ffast-math` at link time is not a very good idea (at least not when linking a shared library). Not sure yet how I can integrate this into my `configure`, but I'm confident that it can be done.

**Comment by mreineck** [comment]
I understand now why this does not cause trouble when working with GNU `autotools`: when generating a shared library, `libtool` automatically strips the dangerous flags from the command line.

Would something similar be possible for the BinaryBuilder as well (i.e. leave the flags alone for the compiling step, but strip them out for linking)?

**Comment by mreineck** [comment]
OK, `libtool` strips `-ffast-math` and `=funsafe-math-optimizations`, but not `-Ofast`. That's most likely why all the PRs on this subject are mentioning `-Ofast`, but not the other flags.

**Comment by xzackli** [comment]
Closed by https://github.com/JuliaPackaging/Yggdrasil/pull/4501, Libsharp is performing the same as the packaged one in Python pixel based on my tests on realistic maps.
